name: Validate ex JSON definitions
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: validate-json
    runs-on: ubuntu-latest
    steps:
      - name: Install jsonlint
        run: npm install jsonlint -g
        
